# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5aa4039b1cf66eeacaa4a6647635ea94e936d9e531d3646920d978cbf54e19db35b6c583637caeefec05c830ff308b553d055536b8e43a78e8aa0789fd46cc5d

test:
  secret_key_base: 7b8989830ef3df52eca605fea07251e5e4b48b0632d360317eb055ba6ee85b0297a88936c4092d117cff076f31f37aab6fb0fa390d8ed2a8bcee97dc25ea9bd5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: d37c9d33760a9116f34ef97381d6cafeb7d8dab20b044be5df89977008c3848f1dbb55929a84fcd9204e8b04370103f571148ee48dfc0c7b97769c6d8da3d67b
